In [3]:
won=int(input())
loss=int(input())
draw=int(input())
total_points=(won*3)+(draw*1)
print(total_points)

 4
 3
 2


14


In [5]:
rasin=int(input("Enter the quantity of rasin: "))
almond=int(input("Enter the quantity of almond: "))
apricot=int(input("Enter the quantity of apricot: "))
total=rasin+almond+apricot
rasin_per=(rasin/total)*100
almond_per=(almond/total)*100
apricot_per=(apricot/total)*100
print(rasin_per)
print(almond_per)
print(apricot_per)

Enter the quantity of rasin:  50
Enter the quantity of almond:  60
Enter the quantity of apricot:  20


38.46153846153847
46.15384615384615
15.384615384615385


In [7]:
num=int(input("Enter the number: "))
if(num%2==0):
    print("even number")
else:
    print("odd number")

Enter the number:  3


odd number


In [9]:
age=int(input("Enter the person's age: "))
if(age>18):
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter the person's age:  12


Not eligible to vote


In [11]:
#prime number
num=int(input("Enter the number: "))
flag=0
for i in range(2,num):
    if(num%i==0):
        flag=0
        break
    else:
        flag=1
if(flag==1):
    print("It is a prime number")
else:
    print("It is not a prime number")

Enter the number:  7


It is a prime number


In [12]:
num1=int(input())
num2=int(input())
if(num1>num2):
    print(num1)
else:
    print(num2)

 3
 4


4


In [14]:
num=int(input("Enter the number: "))
if(num>0):
    print("It is a positive number")
elif(num<0):
    print("It is a negative number")
else:
    print("The number is 0")

Enter the number:  3


It is a positive number


In [15]:
num=int(input("Enter the number"))
if(num%5==0):
    Print("The given number is divisible by 5")
else:
    print("The given number is not divisible by 5")

Enter the number 56


The given number is not divisible by 5


In [18]:
a=int(input("Enter a value: "))
b=int(input("Enter b value: "))
c=int(input("Enter c value: "))
if(a>b and a>c):
    print("The greatest number is:",a)
elif(b>a and b>c):
    print("The greatest number is:",b)
else:
    print("The greatest number is:",c)

Enter a value:  5
Enter b value:  8
Enter c value:  10


The greatest number is: 10


In [20]:
#ATM
account_balance=float(input("Enter the current account Balance: "))
withdraw_amount=int(input("Enter the amount to withdraw: "))
remaining_balance=account_balance-withdraw_amount
if(withdraw_amount>account_balance):
    print("Insufficient amount")
else:
    print("The current amount after withdrawal is",remaining_balance)

Enter the current account Balance:  5000
Enter the amount to withdraw:  2000


The current amount after withdrawal is 3000.0


In [5]:
import numpy as np
print("1D array")
ar=np.array([10,20,30,40])
print(ar)
print("2D array")
ar1=np.array([[10,20],[20,30]])
print(ar1)
print("3D array")
ar2=np.array([[[10,20,30],[9,7,45]],[[23,76,98],[67,98,10]]])
print(ar2)

1D array
[10 20 30 40]
2D array
[[10 20]
 [20 30]]
3D array
[[[10 20 30]
  [ 9  7 45]]

 [[23 76 98]
  [67 98 10]]]


In [14]:
import numpy as np                                                                            #17/03/25
import pandas as pd

In [4]:
list=[10,20,30,40]
print(list)
arr=np.array(list)
print(arr)

[10, 20, 30, 40]
[10 20 30 40]


In [8]:
a=np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [31]:
a4=np.array(np.random.randint(1,11,6))
print(a4)

[ 3  9  3  8  5 10]


In [13]:
b=np.array(np.random.randint(0,2,5))
print(b)

[0 1 1 1 0]


In [14]:
c=np.array([1,2,3,4,5,6])
print(c)
np.reshape(c,(2,3))

[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
[(a+b) for a,b in zip([1,2,3],[4,5,6])]

[5, 7, 9]

In [18]:
d=np.array([3,7,2,9,5])
print(d)
print("The max number in an array is",np.max(d))
print("The min number in an array is",np.min(d))

[3 7 2 9 5]
The max number in an array is 9
The min number in an array is 2


In [21]:
e=np.array([10,20,30,40,50])
print(e)
print("The mean is",np.mean(e))
print("The standard deviation is",np.std(e))

[10 20 30 40 50]
The mean is 30.0
The standard deviation is 14.142135623730951


In [25]:
# printing the numbers greater than 4 in an array
f=np.array([1,3,5,7,9])
for num in f:
    if(num>4):
        print(num,end=" ")

5 7 9 

In [28]:
#multiplication of 2 matrices
g=np.array([[1,2],[3,4]])
h=np.array([[5,6],[7,8]])
print(np.matmul(g,h))
print(g@h)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [3]:
 #Find the value of the function                                                                               #18/3/25
li=[2,-1,1]
for x in li:
    fun=(x**2)+(3*x)-4
    print("The value of the function at x=",x,"is",fun)

The value of the function at x= 2 is 6
The value of the function at x= -1 is -6
The value of the function at x= 1 is 0


In [11]:
#finding whether the x is a root of the given function or not
import math
def root(a,b,c,x):
    r=(-b+math.sqrt((b**2)-(4*a*c)))/2*a
    r1=(-b-math.sqrt((b**2)-(4*a*c)))/2*a
    if(x==r or x==r1):
        return True
    return False
li=[2,-1,1]
a=1
b=3
c=-4
for x in li:
    if(root(a,b,c,x)):
        print(x, "is the root of the given function.")

1 is the root of the given function.


In [12]:
won=int(input())
loss=int(input())
draw=int(input())
total_points=(won*3)+(draw*1)
print(total_points)

 4
 3
 1


13


In [13]:
apples=int(input("Enter the number of apples: "))
oranges=int(input("Enter the number of oranges: "))
bananas=int(input("Enter the number of bananas: "))
total=apples+oranges+bananas
apples_per=(apples/total)*100
oranges_per=(oranges/total)*100
bananas_per=(bananas/total)*100
print(apples_per)
print(oranges_per)
print(bananas_per)

Enter the number of apples:  45
Enter the number of oranges:  65
Enter the number of bananas:  30


32.142857142857146
46.42857142857143
21.428571428571427


In [ ]:
total=int(input("Enter total number of participants in a game:"))
math=int(input("Enter total number of math majors in a game:"))
economic=int(input("Enter total number of economic majors in a game:"))
physics=int(input("Enter total number of physics majors in a game:"))


In [18]:
   #"Wikipedia is a free online encylopedia,created by volunteers around the world and hosted by the wikipedia Foundation".Find the number of words in given sentence.                    #19/3/25
str="Wikipedia is a free online encylopedia,createtd by volunteers around the world and hosted by the wikipedia foundation."
cnt=0
for word in str:
    if(word==" " or word==","):
        cnt=cnt+1
print(cnt+1)
        

18


In [20]:
#Write a python code which takes a number and returns a corresponding string of hypens.For example if the number is 3,it will return '---' .
num=int(input())
str=""
for i in range(num):
    str=str+"-"
print(str)

 4


----


In [26]:
#Astring can be called a safe bridge if it has no gaps in it i.e;no spaces.you are supposed to take an input from the users and print whether the string is safe bridge or not.
str=input()

if " " in str:
    print("String is not a Safe bridge")
else:
    print("String is a Safe bridge")


 bvjgiuh


String is a Safe bridge


In [28]:
#count the number of "D".This will be Case sensitive.
#User_String="Debris was scattered all over the place in the densert regarding Denmark."
str="Debris was scattered all over the place in the densert regarding Denmark."  
print(str.count("D"))

2


In [35]:
#check whether a given string is palindrone.
str=input()
str1=""
for i in range(len(str)-1,-1,-1):
    str1=str1+str[i]
if(str==str1):
    print("String is a palindrome")
else:
    print("String is not a palindrome")

 madam


madam
String is a palindrome
